### ISSUE TITLE
Roadmap: openapi-model 1.0

### ISSUE THREAD

**Issue by mykulyak** [fresha/api-tools#137]
# Overview

This issue describes the desired functionality of the `@fresha/openapi-model` for versions `1.0`.

## OpenAPI 3.0

1. Make programmatic API conform to coding guidelines

- replace raw attributes with getters  and setters
- replace collection attributes with member functions
- use consistent naming
    - deduplicate interfaces (here I mean e.g. `CallbackModelMap` representing sets of methods operating on collection of models of the same type)
    - replace type aliases with interfaces (they are better for performance and readability)

2. Introduce `Reference` models

- currently, a schema node has the `parent` property which references a node that owns the current node. However, a node may also be referenced from other nodes which do not own it. In this case, the node of interest does not know anything about nodes referring to it.
    - this should be fixed by introducing a `Reference` nodes. Whenever a node is referenced but not owned by another node, there should be a reference node inbetween

Example (current state):

```
OpenAPI:
  Components:
    SomeSchema // this node is owned by the components model
  Paths:
    PathItem:
      Operation:
        RequestBody:
          schema: SomeSchema // currently, this property has value of SomeSchema, but SomeSchema does not know anything about it. This complicates mutations, tree walking, as well as deserialising OpenAPI schemas
```

Example (target state):

```
OpenAPI:
  Components:
    SomeSchema // this node is owned by the components
  Paths:
    PathItem:
      Operation:
        RequestBody:
          Reference<Schema>: // a separate node, referring to SomeSchema
```

This approach will ensure that each node will have a single parent (which will also be an owner of that node).

3. Improve reading / writing code for OpenAPI 3.0

Currently information about e.g. attribute order in the original YAML file is lost after deserialisation. This results in e.g. `openapi-lint` producing much more changes than necessary, because it requires everything to be sorted.

Also, the code of `OpenAPIReader` and `OpeAPIWriter` is cluttered. Partly it is because of inconsistent interface of model classes themselves, but not only. Both classes also lack tests.

4. make models for OpenAPI 3.0 support mutations

By this I mean that adding e.g. a setting ID of some operation should validate its value, and prevent appearing duplicate IDs.

Also, there must be a way to listen for mutation events from the schema itself, which will be useful inside the Designer app.

6. unify programmatic APIs of models for OpenAPI 3.0 and OpenAPI 3.1
